lib/rspectre/auto_corrector.rb, spec/auto_corrector_spec.rb
- This solves a problem where the final line of a heredoc extends beyond
the final line of the expression being removed. Now the entire
expression including the herdoc should be removed.
- Fixes #15
=> Remove heredocs properly when auto correcting

lib/rspectre/source_map.rb
- This stops emitting "Unable to resolve ..." messages since they are
almost all the product of not being able to parse an entire file.
Ideally this would be scoped so that it still emits a warning when
something can't be resolved due to a logic error, but for now this is
an improved user experience.
=> Reduce warning noise

lib/rspectre/auto_corrector.rb
`Parser::Rewriter` is [deprecated](https://github.com/whitequark/parser/blob/fbe0e8cbec557c96b0e0f4a8c5201155ee478284/lib/parser/rewriter.rb#L6), so we should update to `Parser::TreeRewriter`.
=> Remove deprecation warning

rspectre.gemspec
- I have not updated the configuration on this repo in quite some time and the floating constraint has allowed various cop changes that are not compatible with my existing config to occur. This should keep things stable until I change further config.
=> Pin rubocop-* to patch version

lib/rspectre.rb, rspectre.gemspec
- I do not currently rely on `unparser` in any capacity. I believe this is a leftover from an early AST-rewriting-based prototype.
=> Remove `unparser` dependency

lib/rspectre.rb
- Apparently I neglected to ensure that StringIO actually exists. The various codebases I have tested `rspectre` on have it directly or indirectly required already so i did not see the failure until recently testing on a new repository.
=> Explicitly require `stringio`

.rubocop.yml, CHANGELOG.md, README.md, rspectre.gemspec
- `rspectre` now officially only supports non-EOL rubies, 2.5+
=> Drop ruby 2.3 support

.circleci/config.yml, .rubocop.yml, CHANGELOG.md, lib/rspectre/auto_corrector.rb, lib/rspectre/linter.rb, lib/rspectre/linter/unused_shared_setup.rb, lib/rspectre/runner.rb, spec/runner_spec.rb, spec/shared/highlighted_offenses.rb, spec/shared/rspectre_runner.rb, spec/spec_helper.rb
- Closes #30
- Tweaks a few overly aggressive rubocop settings as well.
=> Add success message when `rspectre` succeeds

CHANGELOG.md, lib/rspectre.rb, lib/rspectre/runner.rb, spec/runner_spec.rb, spec/shared/rspectre_runner.rb
- This will help users understand why `rspectre` was unable to complete and will assist in making clear bug reports as well.
- Also mildly simplifies our RSpec invocation code.
- Closes #29
=> Output rspec output on failure

lib/rspectre/source_map.rb
Reverts dgollahon/rspectre#19
In light of #26, this workaround should not be necessary. It would be better to be able to see when `rspectre` cannot locate a node, as long as it is not an overwhelming stream as could be the case before #26.
=> Revert "Reduce warning noise"

.circleci/config.yml, rspectre.gemspec
- As pointed out in #42 (thanks @chiastolite!), `rspectre` uses features from `parser` that are only available in 2.5 (see #21). The APIs that are in use should also be compatible with 3.x and because `parser` is intended to have a permanently stable API (or, as close to that as possible), this can just be changed to >= 2.5 for now.
=> Fix `parser` version constraint

.rubocop.yml, lib/rspectre/linter.rb, lib/rspectre/offense.rb, rspectre.gemspec
- Upgrade to the latest `rubocop` and `rubocop-rspec` and enable the latest cops.
- Remove `gem.date` specification from the gemspec, per rubocop, since that should get automatically populated instead when the gem is built.
- Upgrade to the latest `pry`.
=> Upgrade development dependencies

.circleci/config.yml, Gemfile
The codeclimate-test-reporter gem is no longer maintained.
See: https://docs.codeclimate.com/docs/configuring-test-coverage
=> Fix codeclimate reporter

.rubocop.yml, lib/rspectre/auto_corrector.rb, rspectre.gemspec
- Started from a simple upgrade by @jaynetics but I edited to enable/disable the relevant new cops to remove the warnings rubocop started spitting out, to suit my preferences, and also addressed the violations.
- Notably requires MFA for gem releases now.
=> Upgrade rubocop

.circleci/config.yml
- Cherry-picked and lightly modified from @jaynetics. He reports that he's used rspectre on Ruby 3.1 and it appears to work fine.
- Also upgrades to CircleCI's 2.1 format.
=> Add Ruby 2.7, 3.0, and 3.1 to test matrix

.circleci/config.yml, .rubocop.yml, CHANGELOG.md, rspectre.gemspec
=> Drop support for ruby 2.6

lib/rspectre/linter.rb
- Now that we are on ruby 2.7, we can take advantage of this new method which is slightly more performant. I doubt it's a bottleneck but it should be a slight win.
=> Use `#bind_call` instead of `#bind` and `#call`

.rubocop.yml, bin/rspectre, lib/rspectre/offense.rb, lib/rspectre/runner.rb, rspectre.gemspec
- Enables all new cops that I think are reasonable, disables a few that I think that aren't, and simplifies some config that was actually re-specifying the default. Also disables irrelevant departments by department instead of individually.
=> Upgrade `rubocop` and `rubocop-rspec` to latest versions

rspectre.gemspec
- This is just barely ahead of latest `rubocop` so my assumption is that this version constraint shouldn't present a conflict for most adopters. `parser` often has meaningful bugs that do get fixed so I think that unless someone has trouble running things (in which case I am open to relaxing it) it's best to just move to latest and rule out various possible bugs.
=> Upgrade `parser` to latest version

bin/rspectre, lib/rspectre.rb, lib/rspectre/auto_corrector.rb, lib/rspectre/keyword_struct.rb, lib/rspectre/linter.rb, lib/rspectre/node.rb, lib/rspectre/offense.rb, lib/rspectre/runner.rb, lib/rspectre/source_map.rb, lib/rspectre/source_map/parser.rb, lib/rspectre/tracker.rb, rspectre.gemspec
- Removes `anima` and `concord` and adds a vendored, stripped down version of `anima`. Also removes indirect dependencies on `abstract_type`, `adamantium`, `ice_nine`, `memoizable`, `equalizer`, and `thread_safe` in hopes that this makes the gem more adoptable since it now only depends on `parser` and `rspec`. h/t @bquorning.
=> Remove `anima`, `concord`, and indirect dependencies

.circleci/config.yml, rspectre.gemspec
- Tests the latest 4 minor versions of RSpec on each version of Ruby
- Extracts the main build for ruby 3.2 into a separate build step and centralizes it as the only step that reports to Code Climate. This should make the other steps very marginally faster and I don't see any reason to have multiple collections of the coverage data.
=> Test multiple RSpec versions

lib/rspectre/linter/unused_shared_setup.rb, spec/unused_shared_setup_spec.rb
- When `shared_examples` accepts keyword arguments, we need to forward them properly to the original method in RSpec.
- Author @bquorning originally from #62 
- Note [@dgollahon] this partially breaks ruby 2.7 support in [one specific edge case](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#:~:text=If%20your%20code%20doesn%E2%80%99t%20have%20to%20run%20on%20Ruby%202.6%20or%20older%2C%20you%20may%20try%20the%20new%20style%20in%20Ruby%202.7.%20In%20almost%20all%20cases%2C%20it%20works.%20Note%20that%2C%20however%2C%20there%20are%20unfortunate%20corner%20cases%20as%20follows%3A) so I will follow this up with a more complete fix
=> Fix keyword block argument forwarding in Ruby 3.x

lib/rspectre/linter.rb, lib/rspectre/linter/unused_shared_setup.rb
- This should always be safe to do and may be required depending on the method we are hijacking. I did not do this previously due to differences in 2.7 and later versions of ruby but now that [ruby 2.7 is no longer supported](https://github.com/dgollahon/rspectre/pull/72) it makes sense to do this everywhere.
- Related to https://github.com/dgollahon/rspectre/pull/71
- Closes https://github.com/dgollahon/rspectre/issues/46
=> Generically forward keyword arguments

lib/rspectre/keyword_struct.rb, spec/keyword_struct_spec.rb
- I neglected to implement #hash which breaks `Set` (and `Hash`) based equality operations. This is now fixed.
- Also adds basic test coverage which I should have started with originally.
=> Fix KeywordStruct and add test coverage

.circleci/config.yml
- Separate into a separate build step to optimize the main, slowest step.
- Remove from all the variant steps since we only need run of this.
=> Refactor rubocop usage in build

lib/rspectre/node.rb, lib/rspectre/source_map.rb, spec/unused_let_spec.rb
- We prefer finding `block` nodes because they wrap the `send`. There are cases, however, like with a block pass where we actually do want the `send`. So we can just search for `block` nodes and, if we don't find a match, search for `send` as a fallback.
- Closes #60
=> Find block-pass nodes correctly

spec/shared/highlighted_offenses.rb
- Previously STDERR was entirely suppressed. This is suboptimal when debugginb because rspectre is being run in another process during these tests and there is no good way to see obvious warnings or failures otherwise.
=> Improve spec legibility when there are failures

CHANGELOG.md, lib/rspectre/linter.rb, spec/shared/highlighted_offenses.rb, spec/shared/rspectre_runner.rb, spec/unused_let_spec.rb
- When running with `$VERBOSE` set to `true`, rspectre generates a very large # of method redefinition warnings. We can suppress those by removing the method before redefining it. This is very slightly less performant but I think it's worth it.
- Also enforces that we have no STDERR output in CI. Required slightly modifying a couple of spec examples that triggered warnings.
=> Suppress method redefinition warnings

.circleci/config.yml, README.md, rspectre.gemspec
See https://endoflife.date/ruby and https://rubygems.org/gems/rspec/versions
For `gem.add_development_dependency('rubocop-factory_bot', '!= 2.26.0')` change take a look at https://github.com/rubocop/rubocop-rspec/issues/1916
=> Rotate `ruby` and `rspec` versions

bin/console, rspectre.gemspec
- `irb` has caught up with pry in all the features I care about, remove `pry` as a dependency.
=> Remove `pry` as a development dependency

.rubocop.yml, lib/rspectre/linter/unused_let.rb, lib/rspectre/linter/unused_shared_setup.rb, rspectre.gemspec
- Also sorts the .rubocop.yml entries and enables new cops
=> Upgrade `rubocop` and `rubocop-rspec` to latest

.circleci/config.yml, lib/rspectre.rb, lib/rspectre/auto_corrector.rb, lib/rspectre/source_map/parser.rb, rspectre.gemspec, spec/runner_spec.rb, spec/unused_let_spec.rb
- Adds `prism` as a dependency to be used on ruby 3.3+. The `parser` is kept to support ruby 3.1 and 3.2 for now.
=> Add support for ruby 3.4

CHANGELOG.md, lib/rspectre/linter/unused_shared_setup.rb, spec/unused_shared_setup_spec.rb
- RSpec forwards a set of positional arguments and converts them to/from keyword as necessary. They have a helper to do this. The way I was forwarding the arguments was incompatible with this in a few niche cases where examples included each other and one was using keyword arguments and the otherw as not.
=> Fix shared example argument forwarding
